const pizzas = [
    {
        id: 1,
        name: 'Pizza Margherita',
        price: 5.00,
        description: 'Pizza margherita with tomato sauce',
        image: 'https://images.unsplash.com/photo-1644398324665-57647e829ca2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=880&q=80',
        ingredients: [
            'tomato sauce',
            'mozzarella',
            'basil',
            'oregano',
            'parmesan',
        ],
        inCart: false,
        nrOfItemsInCart: 0,
        extraPrice: 0,
        extraIngredients: [
            {
                id: 1,
                name: 'Extra Mozzarella',
                price: 0.50,
                checked: false,
            },
            {
                id: 2,
                name: 'Extra Basil',
                price: 0.50,
                checked: false,
            },
            {
                id: 3,
                name: 'Extra Oregano',
                price: 0.50,
                checked: false,
            },
            {
                id: 4,
                name: 'Extra Parmesan',
                price: 0.50,
                checked: false,
            },
            {
                id: 5,
                name: 'Extra Ham',
                price: 0.50,
                checked: false,
            },
            {
                id: 6,
                name: 'Extra Salami',
                price: 0.50,
                checked: false,
            },
            {
                id: 7,
                name: 'Extra Pepperoni',
                price: 0.50,
                checked: false,
            }
        ],
    },
    {
        id: 2,
        name: 'Pizza Napoletana',
        price: 6.00,
        description: 'Pizza napoletana with ham, salami, and pepperoni',
        image: 'https://images.unsplash.com/photo-1564936281291-294551497d81?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1052&q=80',
        ingredients: [
            'tomato sauce',
            'mozzarella',
            'ham',
            'salami',
            'pepperoni',
        ],
        inCart: false,
        nrOfItemsInCart: 0,
        extraPrice: 0,
        extraIngredients: [
            {
                id: 1,
                name: 'Extra Mozzarella',
                price: 0.50,
                checked: false,
            },
            {
                id: 2,
                name: 'Extra Basil',
                price: 0.50,
                checked: false,
            },
            {
                id: 3,
                name: 'Extra Oregano',
                price: 0.50,
                checked: false,
            },
            {
                id: 4,
                name: 'Extra Parmesan',
                price: 0.50,
                checked: false,
            },
            {
                id: 5,
                name: 'Extra Ham',
                price: 0.50,
                checked: false,
            },
            {
                id: 6,
                name: 'Extra Salami',
                price: 0.50,
                checked: false,
            },
            {
                id: 7,
                name: 'Extra Pepperoni',
                price: 0.50,
                checked: false,
            }
        ],
    },
    {
        id: 3,
        name: 'Pizza Capricciosa',
        price: 7.00,
        description: 'Pizza capricciosa with ham, salami, and pepperoni',
        image: 'https://images.unsplash.com/photo-1585238342024-78d387f4a707?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=880&q=80',
        ingredients: [
            'tomato sauce',
            'mozzarella',
            'ham',
            'salami',
            'pepperoni',
        ],
        inCart: false,
        nrOfItemsInCart: 0,
        extraPrice: 0,
        extraIngredients: [
            {
                id: 1,
                name: 'Extra Mozzarella',
                price: 0.50,
                checked: false,
            },
            {
                id: 2,
                name: 'Extra Basil',
                price: 0.50,
                checked: false,
            },
            {
                id: 3,
                name: 'Extra Oregano',
                price: 0.50,
                checked: false,
            },
            {
                id: 4,
                name: 'Extra Parmesan',
                price: 0.50,
                checked: false,
            },
            {
                id: 5,
                name: 'Extra Ham',
                price: 0.50,
                checked: false,
            },
            {
                id: 6,
                name: 'Extra Salami',
                price: 0.50,
                checked: false,
            },
            {
                id: 7,
                name: 'Extra Pepperoni',
                price: 0.50,
                checked: false,
            }
        ],
    },
    {
        id: 4,
        name: 'Pizza Funghi',
        price: 8.00,
        description: 'Pizza funghi with ham, salami, and pepperoni',
        image: 'https://images.unsplash.com/photo-1527133256227-fc3549f55332?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=880&q=80',
        ingredients: [
            'tomato sauce',
            'mozzarella',
            'ham',
            'salami',
            'pepperoni',
        ],
        inCart: false,
        nrOfItemsInCart: 0,
        extraPrice: 0,
        extraIngredients: [
            {
                id: 1,
                name: 'Extra Mozzarella',
                price: 0.50,
                checked: false,
            },
            {
                id: 2,
                name: 'Extra Basil',
                price: 0.50,
                checked: false,
            },
            {
                id: 3,
                name: 'Extra Oregano',
                price: 0.50,
                checked: false,
            },
            {
                id: 4,
                name: 'Extra Parmesan',
                price: 0.50,
                checked: false,
            },
            {
                id: 5,
                name: 'Extra Ham',
                price: 0.50,
                checked: false,
            },
            {
                id: 6,
                name: 'Extra Salami',
                price: 0.50,
                checked: false,
            },
            {
                id: 7,
                name: 'Extra Pepperoni',
                price: 0.50,
                checked: false,
            }
        ],
    },
]

export default pizzas